name: CI
on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]
    tags: ["*"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=10m
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
          tar -zxvf gitleaks_8.18.0_linux_x64.tar.gz -C /tmp/
          
          sudo mv /tmp/gitleaks /usr/local/bin/
      - name: gitleaks
        run: |
          gitleaks detect  -v --redact --no-git -i ./.gitleaksignore
  build-and-deploy:
    name: Build and Deploy
    permissions:
      contents: read
      packages: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: olegtarasov/get-tag@v2.1
        id: tag-name
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7
      - name: Build and publish tag docker image
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}:${{ env.GIT_TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and publish sha docker image
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/') == false
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}:sha-${{ env.SHA }}-${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}